# Generated by Django 4.2.1 on 2023-05-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
