# Generated by Django 4.2.1 on 2026-03-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0002_project_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('other', 'Other'), ('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('job_category', models.CharField(choices=[('HR', 'HR'), ('SD', 'Software Dev'), ('TE', 'Tester')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
